# Generated by Django 2.1.5 on 2019-02-26 08:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0024_auto_20190226_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TimeField(default=datetime.datetime(2019, 2, 26, 2, 23, 17, 584626))),
                ('created_when', models.DateField(default=datetime.datetime(2019, 2, 26, 2, 23, 17, 584626))),
                ('disabled', models.BooleanField(default=False)),
                ('disabled_at', models.TimeField(blank=True, default=None, editable=False, null=True)),
                ('disabled_when', models.DateField(blank=True, default=None, editable=False, null=True)),
                ('disabled_reason', models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Indique la razón para inhabilitar este producto')),
                ('dropped', models.BooleanField(default=False)),
                ('dropped_at', models.TimeField(blank=True, default=None, editable=False, null=True)),
                ('dropped_when', models.DateField(blank=True, default=None, editable=False, null=True)),
                ('dropped_reason', models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Especifique la razón para eliminar este objeto')),
                ('name', models.CharField(default=None, max_length=254, unique=True, verbose_name='MiNegocito v0.1a')),
                ('created_by_user', models.ForeignKey(db_column='created_by_user', default=None, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='brands_created_by', to='users.Users', verbose_name='Created by')),
            ],
            options={
                'permissions': (('Buscar [action=#/brands/find]', 'Can view brands'), ('Agregar [action=#/brands/add]', 'Can add brands'), ('Editar [action=#/brands/edit]', 'Can edit brands'), ('Eliminar [action=#/brands/delete]', 'Can delete brands')),
            },
        ),
    ]
